#ifndef SG_D_H
#define SG_D_H
enum
{
	INVALID_TCP_HEADER_LENGTH = 0x100,
	INVALID_IP_HEADER_LENGTH,
	TRANSPORT_PROTOCOL_NOT_SUPPORTED,
	INTERNET_PROTOCOL_NOT_SUPPORTED,
	NOT_AMF_SO,
	MSG_PROCD,
	NOT_TYPE_1
};
#endif